### ISSUE TITLE
`controller/LikeController.js`에 대한 제안

### ISSUE THREAD

**Issue by autroshot** [alsrud991026/bookstore-service#11]
현재 좋아요를 추가하거나 제거하기 전에 요청의 유저와 도서 id가 DB에 있는지 확인하고 있습니다. 이 로직을 제거하는 것이 어떨까 싶습니다. 대신 DB에서 던지는 오류를 확인하여 로직을 대신할 수 있습니다.

DB에서 외래키 제약조건이 제대로 설정되어 있다면, 존재하지 않는 외래키로 좋아요를 추가하고자 시도하면 오류가 발생할 것입니다.

발생한 오류는 `error.errno`를 통해 오류의 종류를 파악할 수 있습니다. 예를 들어 유니크 조건을 위반하면 다음과 같은 오류가 발생합니다.

```
Error: Duplicate entry 'test@mail.com' for key 'email_UNIQUE'
    at PromisePool.execute (C:\workspace\programmers\bookstore\node_modules\mysql2\promise.js:374:22)
    at C:\workspace\programmers\bookstore\services\user.ts:13:20
    at Generator.next (<anonymous>)
    at C:\workspace\programmers\bookstore\services\user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\workspace\programmers\bookstore\services\user.ts:4:12)
    at C:\workspace\programmers\bookstore\services\user.ts:6:68
    at C:\workspace\programmers\bookstore\utils\db.ts:12:34
    at Generator.next (<anonymous>)
    at C:\workspace\programmers\bookstore\utils\db.ts:8:71 {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sql: '\n' +
    '            INSERT INTO "users" ("email", "password", "salt") \n' +
    '            VALUES (?, ?, ?)\n' +
    '            ',
  sqlState: '23000',
  sqlMessage: "Duplicate entry 'test@mail.com' for key 'email_UNIQUE'"
}
```

외래키 조건 위반의 `errno`는 `1452`인 것 같은데, 한 번 확인해 보시기 바랍니다.

이 방식의 단점은 유저 id가 없는지, 도서 id가 없는지 구분하려면 DB에서 던지는 오류 메시지를 확인해야 한다는 점입니다. 대신 쿼리 횟수 자체가 줄어든다는 장점이 있습니다.

장단점이 있으므로 본인의 판단 하에 도입하시면 될 것 같습니다.

**Comment by alsrud991026** [comment]
조언 감사합니다! 리팩토링 시 꼭 고려해보겠습니다👍
